modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustDoom/VillagerInABucket/issues"
license = "MIT"

[[mods]]
modId = "villagerinabucket"
version = "${version}"
displayName = "Villager In A Bucket"
authors = "JustDoom"
description = '''
Pick them up in a bucket
'''
logoFile = "logo.png"

[[dependencies.villagerinabucket]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villagerinabucket]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "villagerinabucket-common.mixins.json"